
server:
  port:8080

#TODO: mysql
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/mysql
    username : root
    password : root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  #TODO: mail
  mail:
    host: smtp.163.com
    username: 
    password: 
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #TODO: redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      connect-timeout: 1000

#TODO: OSS
aliyun:
  endpoint: 
  accessKeyId: 
  accessKeySecret: 
  bucketName: 
  urlPrefix: 




#sms config
sms:
  server:
    #时限/s
    smsValidTimeInterval: 300
    length: 6
    title: 【帮帮】验证码

pyServer:
  url: http://127.0.0.1:8888
